name: change background

on:
  push:
    branches:
      - featupdate-background

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from background!
