name: dev

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo I am a manual job
